import Vue from "vue";
import Vuex from "vuex";

import _ from "lodash";

Vue.use(Vuex);

export default {
	state: {
		list: [
			{no: 1, name: "フシギダネ	", type1: "くさ	", type2: "どく	", special: "しんりょく	"},
			{no: 2, name: "フシギソウ	", type1: "くさ	", type2: "どく	", special: "しんりょく	"},
			{no: 3, name: "フシギバナ	", type1: "くさ	", type2: "どく	", special: "しんりょく	"},
			{no: 4, name: "ヒトカゲ	", type1: "ほのお	", type2: "	", special: "もうか	"},
			{no: 5, name: "リザード	", type1: "ほのお	", type2: "	", special: "もうか	"},
			{no: 6, name: "リザードン	", type1: "ほのお	", type2: "ひこう	", special: "もうか	"},
			{no: 7, name: "ゼニガメ	", type1: "みず	", type2: "	", special: "げきりゅう	"},
			{no: 8, name: "カメール	", type1: "みず	", type2: "	", special: "げきりゅう	"},
			{no: 9, name: "カメックス	", type1: "みず	", type2: "	", special: "げきりゅう	"},
			{no: 10, name: "キャタピー	", type1: "むし	", type2: "	", special: "りんぷん	"},
			{no: 11, name: "トランセル	", type1: "むし	", type2: "	", special: "だっぴ	"},
			{no: 12, name: "バタフリー	", type1: "むし	", type2: "ひこう	", special: "ふくがん	"},
			{no: 13, name: "ビードル	", type1: "むし	", type2: "どく	", special: "りんぷん	"},
			{no: 14, name: "コクーン	", type1: "むし	", type2: "どく	", special: "だっぴ	"},
			{no: 15, name: "スピアー	", type1: "むし	", type2: "どく	", special: "むしのしらせ	"},
			{no: 16, name: "ポッポ	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 17, name: "ピジョン	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 18, name: "ピジョット	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 19, name: "コラッタ	", type1: "ノーマル	", type2: "	", special: "にげあし	"},
			{no: 20, name: "ラッタ	", type1: "ノーマル	", type2: "	", special: "にげあし	"},
			{no: 21, name: "オニスズメ	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 22, name: "オニドリル	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 23, name: "アーボ	", type1: "どく	", type2: "	", special: "いかく	"},
			{no: 24, name: "アーボック	", type1: "どく	", type2: "	", special: "いかく	"},
			{no: 25, name: "ピカチュウ	", type1: "でんき	", type2: "	", special: "せいでんき	"},
			{no: 26, name: "ライチュウ	", type1: "でんき	", type2: "	", special: "せいでんき	"},
			{no: 27, name: "サンド	", type1: "じめん	", type2: "	", special: "すながくれ	"},
			{no: 28, name: "サンドパン	", type1: "じめん	", type2: "	", special: "すながくれ	"},
			{no: 29, name: "ニドラン♀	", type1: "どく	", type2: "	", special: "どくのトゲ	"},
			{no: 30, name: "ニドリーナ	", type1: "どく	", type2: "	", special: "どくのトゲ	"},
			{no: 31, name: "ニドクイン	", type1: "どく	", type2: "じめん	", special: "どくのトゲ	"},
			{no: 32, name: "ニドラン♂	", type1: "どく	", type2: "	", special: "どくのトゲ	"},
			{no: 33, name: "ニドリーノ	", type1: "どく	", type2: "	", special: "どくのトゲ	"},
			{no: 34, name: "ニドキング	", type1: "どく	", type2: "じめん	", special: "どくのトゲ	"},
			{no: 35, name: "ピッピ	", type1: "フェアリー	", type2: "	", special: "メロメロボディ	"},
			{no: 36, name: "ピクシー	", type1: "フェアリー	", type2: "	", special: "メロメロボディ	"},
			{no: 37, name: "ロコン	", type1: "ほのお	", type2: "	", special: "もらいび	"},
			{no: 38, name: "キュウコン	", type1: "ほのお	", type2: "	", special: "もらいび	"},
			{no: 39, name: "プリン	", type1: "ノーマル	", type2: "フェアリー	", special: "メロメロボディ	"},
			{no: 40, name: "プクリン	", type1: "ノーマル	", type2: "フェアリー	", special: "メロメロボディ	"},
			{no: 41, name: "ズバット	", type1: "どく	", type2: "ひこう	", special: "せいしんりょく	"},
			{no: 42, name: "ゴルバット	", type1: "どく	", type2: "ひこう	", special: "せいしんりょく	"},
			{no: 43, name: "ナゾノクサ	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 44, name: "クサイハナ	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 45, name: "ラフレシア	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 46, name: "パラス	", type1: "むし	", type2: "くさ	", special: "ほうし	"},
			{no: 47, name: "パラセクト	", type1: "むし	", type2: "くさ	", special: "ほうし	"},
			{no: 48, name: "コンパン	", type1: "むし	", type2: "どく	", special: "ふくがん	"},
			{no: 49, name: "モルフォン	", type1: "むし	", type2: "どく	", special: "りんぷん	"},
			{no: 50, name: "ディグダ	", type1: "じめん	", type2: "	", special: "すながくれ	"},
			{no: 51, name: "ダグトリオ	", type1: "じめん	", type2: "	", special: "すながくれ	"},
			{no: 52, name: "ニャース	", type1: "ノーマル	", type2: "	", special: "ものひろい	"},
			{no: 53, name: "ペルシアン	", type1: "ノーマル	", type2: "	", special: "じゅうなん	"},
			{no: 54, name: "コダック	", type1: "みず	", type2: "	", special: "しめりけ	"},
			{no: 55, name: "ゴルダック	", type1: "みず	", type2: "	", special: "しめりけ	"},
			{no: 56, name: "マンキー	", type1: "かくとう	", type2: "	", special: "やるき	"},
			{no: 57, name: "オコリザル	", type1: "かくとう	", type2: "	", special: "やるき	"},
			{no: 58, name: "ガーディ	", type1: "ほのお	", type2: "	", special: "いかく	"},
			{no: 59, name: "ウインディ	", type1: "ほのお	", type2: "	", special: "いかく	"},
			{no: 60, name: "ニョロモ	", type1: "みず	", type2: "	", special: "ちょすい	"},
			{no: 61, name: "ニョロゾ	", type1: "みず	", type2: "	", special: "ちょすい	"},
			{no: 62, name: "ニョロボン	", type1: "みず	", type2: "かくとう	", special: "ちょすい	"},
			{no: 63, name: "ケーシィ	", type1: "エスパー	", type2: "	", special: "シンクロ	"},
			{no: 64, name: "ユンゲラー	", type1: "エスパー	", type2: "	", special: "シンクロ	"},
			{no: 65, name: "フーディン	", type1: "エスパー	", type2: "	", special: "シンクロ	"},
			{no: 66, name: "ワンリキー	", type1: "かくとう	", type2: "	", special: "こんじょう	"},
			{no: 67, name: "ゴーリキー	", type1: "かくとう	", type2: "	", special: "こんじょう	"},
			{no: 68, name: "カイリキー	", type1: "かくとう	", type2: "	", special: "こんじょう	"},
			{no: 69, name: "マダツボミ	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 70, name: "ウツドン	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 71, name: "ウツボット	", type1: "くさ	", type2: "どく	", special: "ようりょくそ	"},
			{no: 72, name: "メノクラゲ	", type1: "みず	", type2: "どく	", special: "クリアボディ	"},
			{no: 73, name: "ドククラゲ	", type1: "みず	", type2: "どく	", special: "クリアボディ	"},
			{no: 74, name: "イシツブテ	", type1: "いわ	", type2: "じめん	", special: "いしあたま	"},
			{no: 75, name: "ゴローン	", type1: "いわ	", type2: "じめん	", special: "いしあたま	"},
			{no: 76, name: "ゴローニャ	", type1: "いわ	", type2: "じめん	", special: "いしあたま	"},
			{no: 77, name: "ポニータ	", type1: "ほのお	", type2: "	", special: "にげあし	"},
			{no: 78, name: "ギャロップ	", type1: "ほのお	", type2: "	", special: "にげあし	"},
			{no: 79, name: "ヤドン	", type1: "みず	", type2: "エスパー	", special: "どんかん	"},
			{no: 80, name: "ヤドラン	", type1: "みず	", type2: "エスパー	", special: "どんかん	"},
			{no: 81, name: "コイル	", type1: "でんき	", type2: "はがね	", special: "じりょく	"},
			{no: 82, name: "レアコイル	", type1: "でんき	", type2: "はがね	", special: "じりょく	"},
			{no: 83, name: "カモネギ	", type1: "ノーマル	", type2: "ひこう	", special: "するどいめ	"},
			{no: 84, name: "ドードー	", type1: "ノーマル	", type2: "ひこう	", special: "にげあし	"},
			{no: 85, name: "ドードリオ	", type1: "ノーマル	", type2: "ひこう	", special: "にげあし	"},
			{no: 86, name: "パウワウ	", type1: "みず	", type2: "	", special: "あついしぼう	"},
			{no: 87, name: "ジュゴン	", type1: "みず	", type2: "こおり	", special: "あついしぼう	"},
			{no: 88, name: "ベトベター	", type1: "どく	", type2: "	", special: "あくしゅう	"},
			{no: 89, name: "ベトベトン	", type1: "どく	", type2: "	", special: "あくしゅう	"},
			{no: 90, name: "シェルダー	", type1: "みず	", type2: "	", special: "シェルアーマー	"},
			{no: 91, name: "パルシェン	", type1: "みず	", type2: "こおり	", special: "シェルアーマー	"},
			{no: 92, name: "ゴース	", type1: "ゴースト	", type2: "どく	", special: "ふゆう	"},
			{no: 93, name: "ゴースト	", type1: "ゴースト	", type2: "どく	", special: "ふゆう	"},
			{no: 94, name: "ゲンガー	", type1: "ゴースト	", type2: "どく	", special: "のろわれボディ	"},
			{no: 95, name: "イワーク	", type1: "いわ	", type2: "じめん	", special: "いしあたま	"},
			{no: 96, name: "スリープ	", type1: "エスパー	", type2: "	", special: "ふみん	"},
			{no: 97, name: "スリーパー　	", type1: "エスパー	", type2: "	", special: "ふみん	"},
			{no: 98, name: "クラブ	", type1: "みず	", type2: "	", special: "かいりきバサミ	"},
			{no: 99, name: "キングラー	", type1: "みず	", type2: "	", special: "かいりきバサミ	"},
			{no: 100, name: "ビリリダマ	", type1: "でんき	", type2: "	", special: "ぼうおん	"},
			{no: 101, name: "マルマイン	", type1: "でんき	", type2: "	", special: "ぼうおん	"},
			{no: 102, name: "タマタマ	", type1: "くさ	", type2: "エスパー	", special: "ようりょくそ	"},
			{no: 103, name: "ナッシー	", type1: "くさ	", type2: "エスパー	", special: "ようりょくそ	"},
			{no: 104, name: "カラカラ	", type1: "じめん	", type2: "	", special: "いしあたま	"},
			{no: 105, name: "ガラガラ	", type1: "じめん	", type2: "	", special: "いしあたま	"},
			{no: 106, name: "サワムラー	", type1: "かくとう	", type2: "	", special: "じゅうなん	"},
			{no: 107, name: "エビワラー	", type1: "かくとう	", type2: "	", special: "するどいめ	"},
			{no: 108, name: "ベロリンガ	", type1: "ノーマル	", type2: "	", special: "マイペース	"},
			{no: 109, name: "ドガース	", type1: "どく	", type2: "	", special: "ふゆう	"},
			{no: 110, name: "マタドガス	", type1: "どく	", type2: "	", special: "ふゆう	"},
			{no: 111, name: "サイホーン	", type1: "じめん	", type2: "いわ	", special: "ひらいしん	"},
			{no: 112, name: "サイドン	", type1: "じめん	", type2: "いわ	", special: "ひらいしん	"},
			{no: 113, name: "ラッキー	", type1: "ノーマル	", type2: "	", special: "しぜんかいふく	"},
			{no: 114, name: "モンジャラ	", type1: "くさ	", type2: "	", special: "ようりょくそ	"},
			{no: 115, name: "ガルーラ	", type1: "ノーマル	", type2: "	", special: "はやおき	"},
			{no: 116, name: "タッツー	", type1: "みず	", type2: "	", special: "すいすい	"},
			{no: 117, name: "シードラ	", type1: "みず	", type2: "	", special: "どくのトゲ	"},
			{no: 118, name: "トサキント	", type1: "みず	", type2: "	", special: "すいすい	"},
			{no: 119, name: "アズマオウ	", type1: "みず	", type2: "	", special: "すいすい	"},
			{no: 120, name: "ヒトデマン	", type1: "みず	", type2: "	", special: "はっこう	"},
			{no: 121, name: "スターミー	", type1: "みず	", type2: "エスパー	", special: "はっこう	"},
			{no: 122, name: "バリヤード	", type1: "エスパー	", type2: "フェアリー	", special: "ぼうおん	"},
			{no: 123, name: "ストライク	", type1: "むし	", type2: "ひこう	", special: "むしのしらせ	"},
			{no: 124, name: "ルージュラ	", type1: "こおり	", type2: "エスパー	", special: "どんかん	"},
			{no: 125, name: "エレブー	", type1: "でんき	", type2: "	", special: "せいでんき	"},
			{no: 126, name: "ブーバー	", type1: "ほのお	", type2: "	", special: "ほのおのからだ	"},
			{no: 127, name: "カイロス	", type1: "むし	", type2: "	", special: "かいりきバサミ	"},
			{no: 128, name: "ケンタロス	", type1: "ノーマル	", type2: "	", special: "いかく	"},
			{no: 129, name: "コイキング	", type1: "みず	", type2: "	", special: "すいすい	"},
			{no: 130, name: "ギャラドス	", type1: "みず	", type2: "ひこう	", special: "いかく	"},
			{no: 131, name: "ラプラス	", type1: "みず	", type2: "こおり	", special: "ちょすい	"},
			{no: 132, name: "メタモン	", type1: "ノーマル	", type2: "	", special: "じゅうなん	"},
			{no: 133, name: "イーブイ	", type1: "ノーマル	", type2: "	", special: "にげあし	"},
			{no: 134, name: "シャワーズ	", type1: "みず	", type2: "	", special: "ちょすい	"},
			{no: 135, name: "サンダース	", type1: "でんき	", type2: "	", special: "ちくでん	"},
			{no: 136, name: "ブースター	", type1: "ほのお	", type2: "	", special: "もらいび	"},
			{no: 137, name: "ポリゴン	", type1: "ノーマル	", type2: "	", special: "トレース	"},
			{no: 138, name: "オムナイト	", type1: "いわ	", type2: "みず	", special: "すいすい	"},
			{no: 139, name: "オムスター	", type1: "いわ	", type2: "みず	", special: "すいすい	"},
			{no: 140, name: "カブト	", type1: "いわ	", type2: "みず	", special: "すいすい	"},
			{no: 141, name: "カブトプス	", type1: "いわ	", type2: "みず	", special: "すいすい	"},
			{no: 142, name: "プテラ	", type1: "いわ	", type2: "ひこう	", special: "いしあたま	"},
			{no: 143, name: "カビゴン	", type1: "ノーマル	", type2: "	", special: "めんえき	"},
			{no: 144, name: "フリーザー	", type1: "こおり	", type2: "ひこう	", special: "プレッシャー	"},
			{no: 145, name: "サンダー	", type1: "でんき	", type2: "ひこう	", special: "プレッシャー	"},
			{no: 146, name: "ファイヤー	", type1: "ほのお	", type2: "ひこう	", special: "プレッシャー	"},
			{no: 147, name: "ミニリュウ	", type1: "ドラゴン	", type2: "	", special: "だっぴ	"},
			{no: 148, name: "ハクリュー	", type1: "ドラゴン	", type2: "	", special: "だっぴ	"},
			{no: 149, name: "カイリュー	", type1: "ドラゴン	", type2: "ひこう	", special: "せいしんりょく	"},
			{no: 150, name: "ミュウツー	", type1: "エスパー	", type2: "	", special: "プレッシャー	"},
			{no: 151, name: "ミュウ	", type1: "エスパー	", type2: "	", special: "シンクロ	"},
		],
	},
	mutations: {

	},
	getters: {
			getPokemon: (state: any) => {
				return state.list;
		},
	},
	actions: {
		async setNumber(status: any, params: any) {
			status.commit("setNumber", params);
		},
		async setDiagnosis(status: any, params: any) {
			status.commit("setDiagnosis", params);
		},
	},
};
